export interface DeckSeo {
  metaTitle: string;
  metaDescription: string;
  h1: string;
  h2: string;
  intro: string;
}

export const DECK_SEO: Record<string, DeckSeo> = {
  'free-flashcards-for-biology-cell-biology': {
    metaTitle: 'Cell Biology Flashcards | Free GCSE Biology Cards',
    metaDescription: 'Quiz yourself on organelles, osmosis, active transport and cell division with free Biology flashcards on Flashcard Maker. No account needed, start studying straight away.',
    h1: 'Cell Biology Flashcards',
    h2: 'Free GCSE and A Level Biology Study Cards',
    intro: 'These free cell biology flashcards cover organelle functions, transport mechanisms, and the key differences between cell types. A quick revision tool for GCSE Biology and A Level prep.',
  },
  'free-flashcards-for-biology-photosynthesis': {
    metaTitle: 'Photosynthesis Flashcards | Free A Level Biology Cards',
    metaDescription: 'Revise the light reactions, Calvin cycle and limiting factors with free Biology flashcards on Flashcard Maker. Covers GCSE and A Level photosynthesis topics. No login needed.',
    h1: 'Photosynthesis Questions and Answers',
    h2: 'Free A Level Biology Flashcards',
    intro: 'Work through both stages of photosynthesis, from the light dependent reactions in the thylakoid membranes to the Calvin cycle in the stroma. Free flashcards for GCSE and A Level Biology revision.',
  },
  'free-flashcards-for-biology-dna-protein-synthesis': {
    metaTitle: 'DNA and Protein Synthesis Flashcards | Biology Cards',
    metaDescription: 'Study transcription, translation, DNA replication and the genetic code with free Biology flashcards on Flashcard Maker. Ideal for A Level Biology and AS exam revision.',
    h1: 'DNA and Protein Synthesis Study Cards',
    h2: 'Free A Level Biology Revision Flashcards',
    intro: 'From the double helix to translation at the ribosome, these free flashcards walk you through every step of DNA replication and protein synthesis for A Level Biology.',
  },
  'free-flashcards-for-chemistry-atomic-structure': {
    metaTitle: 'Atomic Structure Flashcards | Free Chemistry Cards',
    metaDescription: 'Test yourself on protons, neutrons, isotopes and electron configuration with free Chemistry flashcards on Flashcard Maker. Great for GCSE and A Level Chemistry students.',
    h1: 'Atomic Structure Flashcards',
    h2: 'Free Chemistry Cards on Flashcard Maker',
    intro: 'Cover sub-atomic particles, electronic configuration, isotopes and the history of atomic models with these free Chemistry flashcards. Great for GCSE and A Level Chemistry revision.',
  },
  'free-flashcards-for-chemistry-chemical-bonding': {
    metaTitle: 'Chemical Bonding Flashcards | Free Chemistry Study Cards',
    metaDescription: 'Revise ionic, covalent and metallic bonding plus intermolecular forces with free Chemistry flashcards on Flashcard Maker. Perfect for GCSE and A Level Chemistry revision.',
    h1: 'Chemical Bonding Questions and Answers',
    h2: 'Free Chemistry Flashcards for GCSE and A Level',
    intro: 'Get confident on ionic bonds, covalent structures and metallic bonding, plus the forces that act between molecules. Free Chemistry flashcards for GCSE and A Level revision.',
  },
  'free-flashcards-for-physics-forces-motion': {
    metaTitle: 'Forces and Motion Flashcards | Free Physics Cards',
    metaDescription: "Practice Newton's laws, velocity, acceleration, momentum and resultant forces with free Physics flashcards on Flashcard Maker. Great for GCSE Physics and A Level mechanics.",
    h1: 'Forces and Motion Flashcards',
    h2: 'Free GCSE Physics Revision Cards',
    intro: "Work through Newton's laws, velocity-time graphs, momentum and resultant forces with these free Physics flashcards. Perfect for GCSE Physics and introductory A Level mechanics.",
  },
  'free-flashcards-for-maths-algebra': {
    metaTitle: 'Algebra Flashcards | Free GCSE Maths Study Cards',
    metaDescription: 'Test yourself on equations, inequalities, quadratics and algebraic manipulation with free Maths flashcards on Flashcard Maker. Great for GCSE Maths and A Level preparation.',
    h1: 'Algebra Study Cards',
    h2: 'Free GCSE Maths Flashcards',
    intro: 'Practice factorising expressions, solving equations and working with algebraic fractions using these free Maths flashcards. Covers the algebra topics that come up most in GCSE exams.',
  },
  'free-flashcards-for-psychology-memory': {
    metaTitle: 'Memory in Psychology Flashcards | Free A Level Cards',
    metaDescription: 'Revise models of memory, types of long term memory, forgetting and eyewitness testimony with free Psychology flashcards on Flashcard Maker. Built for A Level Psychology.',
    h1: 'Memory in Psychology Flashcards',
    h2: 'Free A Level Psychology Revision Cards',
    intro: 'These free Psychology flashcards take you through the multi-store model, working memory model, types of long term memory, and the factors that affect eyewitness recall.',
  },
  'free-flashcards-for-geography-climate-change': {
    metaTitle: 'Climate Change Flashcards | Free GCSE Geography Cards',
    metaDescription: 'Quiz yourself on greenhouse gases, causes of climate change, global impacts and mitigation strategies with free Geography flashcards on Flashcard Maker. No login required.',
    h1: 'Climate Change Flashcards',
    h2: 'Free Geography Cards for GCSE Revision',
    intro: 'From the enhanced greenhouse effect to international climate agreements, these free Geography flashcards give you everything you need to tackle the climate change topic in your GCSE exams.',
  },
  'free-flashcards-for-history-causes-of-ww2': {
    metaTitle: 'Causes of WW2 Flashcards | Free GCSE History Cards',
    metaDescription: 'Revise the long and short term causes of World War Two, the Treaty of Versailles and appeasement with free GCSE History flashcards on Flashcard Maker. No login needed.',
    h1: 'Causes of World War Two Study Cards',
    h2: 'Free GCSE History Revision Flashcards',
    intro: 'Cover the key political and economic factors behind the outbreak of World War Two, from the failures of Versailles to the policy of appeasement, with these free History flashcards.',
  },
  'free-flashcards-for-chemistry-stp': {
    metaTitle: 'Standard Temperature and Pressure Flashcards | Chemistry',
    metaDescription: 'Learn STP definitions, molar volume and gas calculations with free Chemistry flashcards on Flashcard Maker. Great for A Level and university Chemistry students.',
    h1: 'STP Chemistry Flashcards',
    h2: 'Free Cards on Standard Temperature and Pressure',
    intro: 'These free Chemistry flashcards focus on standard temperature and pressure, molar volumes and gas law calculations. Useful for A Level Chemistry and university level study.',
  },
  'free-flashcards-for-chemistry-periodic-table': {
    metaTitle: 'Periodic Table Flashcards | Free Chemistry Revision Cards',
    metaDescription: 'Test yourself on groups, periods, periodic trends and element properties with free Chemistry flashcards on Flashcard Maker. Covers GCSE and A Level content. No sign-up needed.',
    h1: 'Periodic Table Questions and Answers',
    h2: 'Free GCSE and A Level Chemistry Cards',
    intro: 'Revise element groups, periodic trends, reactivity and the properties of key elements with these free Chemistry flashcards. Perfect for GCSE and A Level exam prep.',
  },
  'free-flashcards-for-biology-genetics-evolution': {
    metaTitle: 'Genetics and Evolution Flashcards | Free Biology Cards',
    metaDescription: 'Revise alleles, Punnett squares, natural selection, speciation and inheritance with free Biology flashcards on Flashcard Maker. Covers GCSE and A Level genetics content.',
    h1: 'Genetics and Evolution Flashcards',
    h2: 'Free Biology Cards for GCSE and A Level',
    intro: 'Work through alleles, dominant and recessive inheritance, natural selection and the evidence for evolution using these free Biology flashcards. Ideal for GCSE and A Level revision.',
  },
  'free-flashcards-for-history-world-war-2': {
    metaTitle: 'World War Two Flashcards | Free GCSE History Cards',
    metaDescription: 'Study key battles, events, leaders and turning points of World War Two with free History flashcards on Flashcard Maker. A useful revision tool for GCSE and A Level students.',
    h1: 'World War Two Flashcards',
    h2: 'Free GCSE History Revision Cards',
    intro: 'From the fall of France to the D-Day landings and the Pacific War, these free History flashcards take you through the major events and turning points of the Second World War.',
  },
  'free-flashcards-for-english-literature-macbeth': {
    metaTitle: 'Macbeth Flashcards | Free English Literature Cards',
    metaDescription: 'Test yourself on characters, themes, key quotes and plot events in Macbeth with free English Literature flashcards on Flashcard Maker. No login needed, works on any device.',
    h1: 'Macbeth English Literature Flashcards',
    h2: 'Free GCSE English Literature Study Cards',
    intro: "Cover themes of ambition and power, key character analysis, important quotations and plot events in Shakespeare's Macbeth with these free English Literature flashcards.",
  },
  'free-flashcards-for-biology-nervous-system': {
    metaTitle: 'Nervous System Flashcards | Free Biology Revision Cards',
    metaDescription: 'Revise neurons, synapses, reflex arcs, the brain and the autonomic nervous system with free Biology flashcards on Flashcard Maker. Great for GCSE and A Level Biology.',
    h1: 'Nervous System Study Cards',
    h2: 'Free Biology Flashcards for GCSE and A Level',
    intro: 'These free Biology flashcards take you through the structure of neurons, how synaptic transmission works, and the coordination roles of the central and peripheral nervous system.',
  },
  'free-flashcards-for-psychology-social-influence': {
    metaTitle: 'Social Influence Flashcards | Free A Level Psychology',
    metaDescription: "Revise conformity, obedience, Milgram's research and minority influence with free A Level Psychology flashcards on Flashcard Maker. Perfect for exam revision. No sign-up needed.",
    h1: 'Social Influence Questions and Answers',
    h2: 'Free A Level Psychology Cards',
    intro: "From Asch's conformity studies to Milgram's obedience experiments, these free Psychology flashcards cover the key research and theories in social influence for A Level.",
  },
  'free-flashcards-for-computer-science-data-representation': {
    metaTitle: 'Data Representation Flashcards | Free Computer Science',
    metaDescription: 'Practice binary, hexadecimal, ASCII, image and sound representation with free Computer Science flashcards on Flashcard Maker. Covers GCSE and A Level CS content.',
    h1: 'Data Representation Flashcards',
    h2: 'Free Computer Science Revision Cards',
    intro: 'From converting between binary and hexadecimal to understanding how images and sound are stored digitally, these free Computer Science flashcards cover data representation from the ground up.',
  },
  'free-flashcards-for-maths-trigonometry': {
    metaTitle: 'Trigonometry Flashcards | Free GCSE Maths Cards',
    metaDescription: 'Quiz yourself on SOH CAH TOA, the sine rule, cosine rule and trigonometric identities with free Maths flashcards on Flashcard Maker. Great for GCSE and A Level revision.',
    h1: 'Trigonometry Study Cards',
    h2: 'Free Maths Flashcards on Flashcard Maker',
    intro: 'Practice the core trigonometry skills you need for GCSE and A Level Maths, from right angled triangle calculations using SOH CAH TOA to the sine and cosine rules.',
  },
  'free-flashcards-for-physics-electricity-circuits': {
    metaTitle: 'Electricity and Circuits Flashcards | Free Physics Cards',
    metaDescription: "Revise current, voltage, resistance, Ohm's law and circuit components with free Physics flashcards on Flashcard Maker. Covers GCSE and A Level Physics electricity content.",
    h1: 'Electricity and Circuits Flashcards',
    h2: 'Free GCSE Physics Revision Cards',
    intro: "Work through current, voltage, resistance and circuit calculations with these free Physics flashcards. Covers everything from Ohm's law to series and parallel circuits for GCSE Physics.",
  },
  'free-flashcards-for-economics-supply-demand': {
    metaTitle: 'Supply and Demand Flashcards | Free Economics Cards',
    metaDescription: 'Test yourself on supply and demand curves, price elasticity and market equilibrium with free Economics flashcards on Flashcard Maker. Great for A Level Economics students.',
    h1: 'Supply and Demand Flashcards',
    h2: 'Free A Level Economics Study Cards',
    intro: 'Cover the laws of supply and demand, price elasticity, market equilibrium and the effects of government intervention with these free A Level Economics flashcards.',
  },
  'free-flashcards-for-anatomy-musculoskeletal-system': {
    metaTitle: 'Musculoskeletal System Flashcards | Free Anatomy Cards',
    metaDescription: 'Revise bones, joints, muscles and movement with free Anatomy flashcards on Flashcard Maker. Covers musculoskeletal anatomy for nursing, medicine and sport science students.',
    h1: 'Musculoskeletal System Flashcards',
    h2: 'Free Anatomy Revision Cards',
    intro: 'These free Anatomy flashcards cover the bones, joints, ligaments and muscles of the musculoskeletal system. A practical revision resource for nursing, medical and sport science students.',
  },
  'free-flashcards-for-anatomy-cardiovascular-system': {
    metaTitle: 'Cardiovascular System Flashcards | Free Anatomy Cards',
    metaDescription: 'Study the heart, blood vessels, blood pressure and cardiac cycle with free Anatomy flashcards on Flashcard Maker. Built for nursing, medicine and A Level Biology students.',
    h1: 'Cardiovascular System Questions and Answers',
    h2: 'Free Anatomy Flashcards on Flashcard Maker',
    intro: 'Learn the structure and function of the heart, the different types of blood vessels, and how blood pressure is regulated with these free Anatomy and Physiology flashcards.',
  },
  'free-flashcards-for-nursing-pharmacology-essentials': {
    metaTitle: 'Pharmacology Flashcards for Nursing | Free Study Cards',
    metaDescription: 'Revise drug classifications, mechanisms of action and routes of administration with free Nursing Pharmacology flashcards on Flashcard Maker. No login needed.',
    h1: 'Nursing Pharmacology Flashcards',
    h2: 'Free Pharmacology Revision Cards for Student Nurses',
    intro: 'These free Nursing Pharmacology flashcards cover drug classes, routes of administration, common side effects and key mechanisms of action. Perfect revision for student nurses.',
  },
  'free-flashcards-for-nursing-patient-assessment': {
    metaTitle: 'Patient Assessment Flashcards | Free Nursing Cards',
    metaDescription: 'Practice clinical assessment techniques, vital signs and NEWS scoring with free Nursing flashcards on Flashcard Maker. Built for student nurses on clinical placement.',
    h1: 'Patient Assessment Study Cards',
    h2: 'Free Nursing Revision Flashcards',
    intro: 'Cover the systematic approach to patient assessment, vital sign interpretation, NEWS scoring and clinical observations with these free Nursing flashcards. Ideal for students preparing for clinical placements.',
  },
  'free-flashcards-for-medicine-immune-system': {
    metaTitle: 'Immune System Flashcards | Free Medical Study Cards',
    metaDescription: 'Revise innate and adaptive immunity, antibodies, lymphocytes and immune responses with free Medical flashcards on Flashcard Maker. Great for medical and nursing students.',
    h1: 'Immune System Flashcards',
    h2: 'Free Medical Science Revision Cards',
    intro: 'From innate defences to adaptive immunity and the role of B and T lymphocytes, these free Medical Science flashcards give you a thorough grounding in how the immune system works.',
  },
  'free-flashcards-for-medicine-common-diseases': {
    metaTitle: 'Common Diseases Flashcards | Free Medical Study Cards',
    metaDescription: 'Study symptoms, causes, risk factors and treatments for common diseases with free Medical flashcards on Flashcard Maker. A practical resource for medical and nursing students.',
    h1: 'Common Diseases Questions and Answers',
    h2: 'Free Medical Flashcards for Students',
    intro: 'Revise the presentations, causes and management of common diseases and conditions with these free Medical flashcards. Useful for medical students, nursing students and health science courses.',
  },
  'free-flashcards-for-biology-ecology': {
    metaTitle: 'Ecology Flashcards | Free GCSE Biology Revision Cards',
    metaDescription: 'Test yourself on ecosystems, food chains, energy transfer and biodiversity with free Biology flashcards on Flashcard Maker. Covers GCSE and A Level Ecology content.',
    h1: 'Ecology Flashcards',
    h2: 'Free GCSE Biology Cards for Ecology Revision',
    intro: 'From food webs and energy pyramids to biodiversity, conservation and the impact of human activity, these free Ecology flashcards cover everything you need for GCSE and A Level Biology.',
  },
  'free-flashcards-for-biology-inheritance': {
    metaTitle: 'Inheritance Flashcards | Free GCSE Biology Cards',
    metaDescription: 'Revise genotype, phenotype, dominant and recessive alleles, sex linkage and Punnett squares with free Biology flashcards on Flashcard Maker. Covers GCSE and A Level content.',
    h1: 'Inheritance in Biology Flashcards',
    h2: 'Free Biology Study Cards on Flashcard Maker',
    intro: 'Work through the key concepts of genetic inheritance, from Mendelian genetics and Punnett squares to sex linked traits and codominance, using these free Biology flashcards.',
  },
  'free-flashcards-for-biology-cellular-respiration': {
    metaTitle: 'Cellular Respiration Flashcards | Free Biology Cards',
    metaDescription: 'Study aerobic and anaerobic respiration, ATP production, glycolysis and the Krebs cycle with free Biology flashcards on Flashcard Maker. Great for A Level Biology revision.',
    h1: 'Cellular Respiration Flashcards',
    h2: 'Free A Level Biology Revision Cards',
    intro: 'These free Biology flashcards cover the full pathway of cellular respiration, from glycolysis and the link reaction through to the electron transport chain and ATP synthesis.',
  },
  'free-flashcards-for-biology-digestive-system': {
    metaTitle: 'Digestive System Flashcards | Free Biology Cards',
    metaDescription: 'Revise the organs, enzymes and processes of digestion with free Biology flashcards on Flashcard Maker. Covers the digestive system for GCSE, A Level and health science.',
    h1: 'Digestive System Study Cards',
    h2: 'Free Biology Flashcards on Digestion',
    intro: 'Learn the structure and function of each organ in the digestive system, the enzymes involved in breaking down food, and how nutrients are absorbed with these free Biology flashcards.',
  },
  'free-flashcards-for-biology-homeostasis': {
    metaTitle: 'Homeostasis Flashcards | Free GCSE Biology Cards',
    metaDescription: 'Test yourself on negative feedback, thermoregulation, blood glucose control and osmoregulation with free Biology flashcards on Flashcard Maker. Perfect for GCSE and A Level.',
    h1: 'Homeostasis Questions and Answers',
    h2: 'Free GCSE Biology Revision Flashcards',
    intro: 'Cover the principles of negative feedback and how the body maintains a stable internal environment, including temperature regulation, blood glucose control and kidney function.',
  },
  'free-flashcards-for-chemistry-rates-of-reaction': {
    metaTitle: 'Rates of Reaction Flashcards | Free Chemistry Cards',
    metaDescription: 'Revise factors affecting reaction rate, activation energy, catalysts and collision theory with free Chemistry flashcards on Flashcard Maker. Built for GCSE and A Level students.',
    h1: 'Rates of Reaction Flashcards',
    h2: 'Free Chemistry Revision Cards on Flashcard Maker',
    intro: 'From collision theory to the effect of temperature and concentration, these free Chemistry flashcards cover all the key factors that influence reaction rates for GCSE and A Level.',
  },
  'free-flashcards-for-chemistry-acids-bases-salts': {
    metaTitle: 'Acids Bases and Salts Flashcards | Free Chemistry Cards',
    metaDescription: 'Practice pH, neutralisation, salt preparation and reactions of acids with free Chemistry flashcards on Flashcard Maker. Covers GCSE and A Level Chemistry. No account needed.',
    h1: 'Acids, Bases and Salts Study Cards',
    h2: 'Free GCSE Chemistry Flashcards',
    intro: 'Quiz yourself on pH, neutralisation reactions, the preparation of salts, and the properties of acids and bases with these free Chemistry flashcards. Ideal for GCSE Chemistry revision.',
  },
  'free-flashcards-for-chemistry-organic-chemistry': {
    metaTitle: 'Organic Chemistry Flashcards | Free A Level Cards',
    metaDescription: 'Revise functional groups, reaction mechanisms, homologous series and nomenclature with free Organic Chemistry flashcards on Flashcard Maker. Perfect for A Level Chemistry.',
    h1: 'Organic Chemistry Flashcards',
    h2: 'Free A Level Chemistry Revision Cards',
    intro: 'Cover functional groups, reaction mechanisms, homologous series and IUPAC nomenclature with these free A Level Organic Chemistry flashcards. A thorough revision tool for exam season.',
  },
  'free-flashcards-for-chemistry-electrolysis': {
    metaTitle: 'Electrolysis Flashcards | Free GCSE Chemistry Cards',
    metaDescription: 'Test yourself on electrodes, electrolytes, half equations and industrial applications of electrolysis with free Chemistry flashcards on Flashcard Maker. Covers GCSE and A Level.',
    h1: 'Electrolysis Questions and Answers',
    h2: 'Free Chemistry Study Cards for GCSE Students',
    intro: 'Revise the principles of electrolysis, electrode reactions, half equations and real world applications like the extraction of aluminium with these free Chemistry flashcards.',
  },
  'free-flashcards-for-chemistry-energy-changes': {
    metaTitle: 'Energy Changes Flashcards | Free Chemistry Revision Cards',
    metaDescription: "Practice exothermic and endothermic reactions, bond enthalpies and Hess's law with free Chemistry flashcards on Flashcard Maker. Great for GCSE and A Level exam revision.",
    h1: 'Energy Changes in Chemistry Flashcards',
    h2: 'Free GCSE and A Level Chemistry Cards',
    intro: "From bond energy calculations to Hess's law and reaction profiles, these free Chemistry flashcards cover the energy changes content you need for GCSE and A Level exams.",
  },
  'free-flashcards-for-physics-waves': {
    metaTitle: 'Waves Flashcards | Free GCSE Physics Revision Cards',
    metaDescription: 'Revise wave properties, reflection, refraction and the electromagnetic spectrum with free Physics flashcards on Flashcard Maker. Great for GCSE and A Level Physics.',
    h1: 'Waves in Physics Flashcards',
    h2: 'Free GCSE Physics Study Cards',
    intro: 'From transverse and longitudinal waves to reflection, refraction, diffraction and the electromagnetic spectrum, these free Physics flashcards cover everything on waves for GCSE and A Level.',
  },
  'free-flashcards-for-physics-radioactivity': {
    metaTitle: 'Radioactivity Flashcards | Free Physics Study Cards',
    metaDescription: 'Study alpha, beta and gamma radiation, half life and nuclear equations with free Physics flashcards on Flashcard Maker. Covers GCSE and A Level Physics content.',
    h1: 'Radioactivity Flashcards',
    h2: 'Free GCSE Physics Cards on Radioactivity',
    intro: 'From the properties of alpha, beta and gamma radiation to half life calculations and nuclear equations, these free Physics flashcards cover radioactivity for GCSE and A Level.',
  },
  'free-flashcards-for-physics-magnetism': {
    metaTitle: 'Magnetism Flashcards | Free Physics Revision Cards',
    metaDescription: 'Revise magnetic fields, electromagnets, the motor effect, transformers and induction with free Physics flashcards on Flashcard Maker. Built for GCSE and A Level students.',
    h1: 'Magnetism and Electromagnetism Flashcards',
    h2: 'Free Physics Cards on Flashcard Maker',
    intro: 'Work through magnetic field lines, the motor effect, solenoids, transformers and electromagnetic induction with these free Physics flashcards. Great for GCSE and A Level Physics revision.',
  },
  'free-flashcards-for-physics-energy-power': {
    metaTitle: 'Energy and Power Flashcards | Free Physics Cards',
    metaDescription: 'Practice energy stores, power calculations, efficiency and renewable energy with free Physics flashcards on Flashcard Maker. Perfect for GCSE Physics revision.',
    h1: 'Energy and Power Study Cards',
    h2: 'Free GCSE Physics Revision Flashcards',
    intro: 'Cover energy stores, energy transfers, power, efficiency and the advantages of different energy sources with these free GCSE Physics flashcards. Includes the key equations and concepts.',
  },
  'free-flashcards-for-maths-geometry': {
    metaTitle: 'Geometry Flashcards | Free GCSE Maths Revision Cards',
    metaDescription: 'Quiz yourself on angles, area, volume, circle theorems and transformations with free Maths flashcards on Flashcard Maker. Great revision for GCSE and A Level Maths.',
    h1: 'Geometry Study Cards',
    h2: 'Free GCSE Maths Geometry Flashcards',
    intro: 'Practice area and volume formulas, angle rules, circle theorems and geometric transformations with these free Maths flashcards. Covers the geometry topics that come up most in GCSE exams.',
  },
  'free-flashcards-for-maths-statistics': {
    metaTitle: 'Statistics Flashcards | Free GCSE Maths Study Cards',
    metaDescription: 'Revise mean, median, mode, standard deviation, probability and data representation with free Maths flashcards on Flashcard Maker. Covers GCSE and A Level Statistics.',
    h1: 'Statistics Questions and Answers',
    h2: 'Free Maths Statistics Cards on Flashcard Maker',
    intro: 'From averages and spread to probability trees and statistical diagrams, these free Maths flashcards cover the statistics content you need for GCSE Maths and A Level Statistics.',
  },
  'free-flashcards-for-maths-calculus': {
    metaTitle: 'Calculus Flashcards | Free A Level Maths Study Cards',
    metaDescription: 'Study differentiation, integration, chain rule, product rule and applications of calculus with free A Level Maths flashcards on Flashcard Maker. No account needed.',
    h1: 'Calculus Revision Flashcards',
    h2: 'Free A Level Maths Cards',
    intro: 'Cover differentiation from first principles, integration techniques, and the practical applications of calculus in A Level Maths with these free revision flashcards.',
  },
  'free-flashcards-for-maths-number': {
    metaTitle: 'Number Flashcards | Free GCSE Maths Revision Cards',
    metaDescription: 'Practice fractions, indices, surds, standard form and prime factors with free Maths flashcards on Flashcard Maker. A solid GCSE Maths revision resource. No login needed.',
    h1: 'Number in Maths Flashcards',
    h2: 'Free GCSE Maths Number Revision Cards',
    intro: 'Brush up on fractions, decimals, indices, standard form, surds and prime factorisation with these free GCSE Maths flashcards. Covers the essential number skills for GCSE exam success.',
  },
  'free-flashcards-for-history-cold-war': {
    metaTitle: 'Cold War Flashcards | Free GCSE History Revision Cards',
    metaDescription: 'Revise superpower tensions, key events and turning points of the Cold War with free History flashcards on Flashcard Maker. Great for GCSE and A Level History revision.',
    h1: 'Cold War Flashcards',
    h2: 'Free History Cards for GCSE and A Level',
    intro: 'From the origins of the Cold War and the Berlin blockade to the Cuban Missile Crisis and the arms race, these free History flashcards cover the major events and themes for your exams.',
  },
  'free-flashcards-for-history-the-holocaust': {
    metaTitle: 'The Holocaust Flashcards | Free GCSE History Cards',
    metaDescription: 'Study the causes, events and impact of the Holocaust with free History flashcards on Flashcard Maker. A thoughtful and thorough revision resource for GCSE History and beyond.',
    h1: 'The Holocaust Flashcards',
    h2: 'Free GCSE History Revision Study Cards',
    intro: 'These free History flashcards cover the persecution of Jewish people and other groups under Nazi rule, from the early anti-Jewish laws to the Final Solution and its lasting legacy.',
  },
  'free-flashcards-for-history-french-revolution': {
    metaTitle: 'French Revolution Flashcards | Free History Cards',
    metaDescription: 'Revise the causes, key events and consequences of the French Revolution with free History flashcards on Flashcard Maker. Covers A Level and GCSE History. No login needed.',
    h1: 'French Revolution Questions and Answers',
    h2: 'Free History Flashcards on Revolutionary France',
    intro: 'Work through the social and economic causes of the French Revolution, the Reign of Terror, the rise of Napoleon and the long term consequences for Europe with these free History flashcards.',
  },
  'free-flashcards-for-history-ancient-rome': {
    metaTitle: 'Ancient Rome Flashcards | Free History Study Cards',
    metaDescription: 'Study the rise and fall of the Roman Empire, Roman society, government and culture with free History flashcards on Flashcard Maker. No login required.',
    h1: 'Ancient Rome History Flashcards',
    h2: 'Free Classical History Revision Cards',
    intro: 'From the Roman Republic to the fall of the Western Empire, these free History flashcards take you through Roman government, society, military campaigns and cultural achievements.',
  },
  'free-flashcards-for-geography-tectonic-hazards': {
    metaTitle: 'Tectonic Hazards Flashcards | Free Geography Cards',
    metaDescription: 'Quiz yourself on plate tectonics, earthquakes, volcanoes and hazard management with free Geography flashcards on Flashcard Maker. Covers GCSE and A Level Geography.',
    h1: 'Tectonic Hazards Flashcards',
    h2: 'Free GCSE Geography Revision Cards',
    intro: 'Cover plate boundaries, earthquake and volcanic processes, the impacts of tectonic hazards and how communities manage risk with these free Geography flashcards. Great for GCSE and A Level.',
  },
  'free-flashcards-for-geography-rivers-coasts': {
    metaTitle: 'Rivers and Coasts Flashcards | Free Geography Cards',
    metaDescription: 'Revise river processes, landforms, coastal erosion, deposition and management with free Geography flashcards on Flashcard Maker. Great for GCSE and A Level Geography students.',
    h1: 'Rivers and Coasts Flashcards',
    h2: 'Free Geography Study Cards on Flashcard Maker',
    intro: 'From drainage basins and river profiles to coastal landforms and management strategies, these free Geography flashcards cover the physical geography you need for GCSE and A Level exams.',
  },
  'free-flashcards-for-english-literature-romeo-and-juliet': {
    metaTitle: 'Romeo and Juliet Flashcards | Free English Lit Cards',
    metaDescription: 'Test yourself on themes, characters, key quotes and plot analysis in Romeo and Juliet with free English Literature flashcards on Flashcard Maker. Perfect for GCSE revision.',
    h1: 'Romeo and Juliet Flashcards',
    h2: 'Free GCSE English Literature Study Cards',
    intro: 'Cover themes of love, fate and family conflict, key character analysis, and important quotations from Romeo and Juliet with these free English Literature flashcards.',
  },
  'free-flashcards-for-english-literature-of-mice-and-men': {
    metaTitle: 'Of Mice and Men Flashcards | Free English Lit Cards',
    metaDescription: 'Revise characters, themes, key quotes and context in Of Mice and Men with free English Literature flashcards on Flashcard Maker. Covers GCSE English Literature content.',
    h1: 'Of Mice and Men Study Cards',
    h2: 'Free English Literature Cards on Flashcard Maker',
    intro: "Explore the themes of dreams, friendship and social inequality in Steinbeck's Of Mice and Men with these free English Literature flashcards. Ideal for GCSE English Literature revision.",
  },
  'free-flashcards-for-english-literature-an-inspector-calls': {
    metaTitle: 'An Inspector Calls Flashcards | Free GCSE English Cards',
    metaDescription: 'Study characters, themes, key quotes and dramatic techniques in An Inspector Calls with free English Literature flashcards on Flashcard Maker. Perfect for GCSE revision.',
    h1: 'An Inspector Calls Flashcards',
    h2: 'Free GCSE English Literature Revision Cards',
    intro: "From the Birling family dynamics to Priestley's socialist message, these free English Literature flashcards cover the key themes, characters and quotations in An Inspector Calls.",
  },
  'free-flashcards-for-psychology-approaches': {
    metaTitle: 'Psychology Approaches Flashcards | Free A Level Cards',
    metaDescription: 'Revise the biological, cognitive, behavioural and psychodynamic approaches with free A Level Psychology flashcards on Flashcard Maker. Perfect for exam revision. No sign-up needed.',
    h1: 'Psychology Approaches Flashcards',
    h2: 'Free A Level Psychology Revision Cards',
    intro: 'Cover the key assumptions, strengths and weaknesses of each major psychological approach, from behaviourism and cognitive psychology to the psychodynamic and humanistic perspectives.',
  },
  'free-flashcards-for-psychology-psychopathology': {
    metaTitle: 'Psychopathology Flashcards | Free A Level Psychology',
    metaDescription: 'Study definitions of abnormality, phobias, depression, OCD and their treatments with free A Level Psychology flashcards on Flashcard Maker. No login required.',
    h1: 'Psychopathology Questions and Answers',
    h2: 'Free A Level Psychology Cards on Flashcard Maker',
    intro: 'Revise definitions of abnormality, the characteristics of phobias, depression and OCD, and the treatments used for each condition with these free A Level Psychology flashcards.',
  },
  'free-flashcards-for-psychology-attachment': {
    metaTitle: 'Attachment Theory Flashcards | Free A Level Psychology',
    metaDescription: "Revise Bowlby's theory, Ainsworth's Strange Situation and types of attachment with free Psychology flashcards on Flashcard Maker. Built for A Level Psychology students.",
    h1: 'Attachment Theory Flashcards',
    h2: 'Free A Level Psychology Revision Study Cards',
    intro: "Cover Bowlby's attachment theory, the Strange Situation experiment, types of attachment and the long term effects of early attachment experiences with these free A Level Psychology flashcards.",
  },
  'free-flashcards-for-computer-science-algorithms': {
    metaTitle: 'Algorithms Flashcards | Free Computer Science Cards',
    metaDescription: 'Practice searching, sorting, complexity and algorithmic thinking with free Computer Science flashcards on Flashcard Maker. Covers GCSE and A Level CS content. No login needed.',
    h1: 'Algorithms and Computational Thinking Flashcards',
    h2: 'Free Computer Science Revision Cards',
    intro: 'Work through common algorithms, sorting methods, Big O notation and the principles of computational thinking with these free Computer Science flashcards. Great for GCSE and A Level CS.',
  },
  'free-flashcards-for-computer-science-networks': {
    metaTitle: 'Computer Networks Flashcards | Free CS Revision Cards',
    metaDescription: 'Revise network topologies, protocols, IP addressing, security and the internet with free Computer Science flashcards on Flashcard Maker. Covers GCSE and A Level Computer Science.',
    h1: 'Computer Networks Study Cards',
    h2: 'Free Computer Science Cards on Flashcard Maker',
    intro: 'From network topologies and the OSI model to protocols, IP addressing and cyber security, these free Computer Science flashcards cover everything you need on networks for GCSE and A Level.',
  },
  'free-flashcards-for-economics-macroeconomics': {
    metaTitle: 'Macroeconomics Flashcards | Free A Level Economics Cards',
    metaDescription: 'Study GDP, inflation, unemployment, fiscal policy and monetary policy with free Macroeconomics flashcards on Flashcard Maker. A great resource for A Level Economics students.',
    h1: 'Macroeconomics Flashcards',
    h2: 'Free A Level Economics Revision Cards',
    intro: 'Cover aggregate demand, aggregate supply, economic growth, inflation and the policy tools used by governments and central banks with these free A Level Macroeconomics flashcards.',
  },
  'free-flashcards-for-law-criminal-law': {
    metaTitle: 'Criminal Law Flashcards | Free Law Revision Study Cards',
    metaDescription: 'Revise actus reus, mens rea, defences and offences against the person with free Law flashcards on Flashcard Maker. Built for A Level Law and university students.',
    h1: 'Criminal Law Flashcards',
    h2: 'Free Law Revision Cards on Flashcard Maker',
    intro: 'Cover the key elements of criminal liability, common offences, defences and the principles of mens rea and actus reus with these free Law flashcards. Useful for A Level Law and first year university.',
  },
  'free-flashcards-for-philosophy-ethics': {
    metaTitle: 'Ethics in Philosophy Flashcards | Free Study Cards',
    metaDescription: 'Revise utilitarianism, deontology, virtue ethics, natural law and applied ethics with free Philosophy flashcards on Flashcard Maker. Great for A Level and university students.',
    h1: 'Ethics and Moral Philosophy Flashcards',
    h2: 'Free Philosophy Revision Cards',
    intro: 'From Kantian deontology and utilitarian theory to virtue ethics and applied moral dilemmas, these free Philosophy flashcards cover the major ethical theories and debates.',
  },
  'free-flashcards-for-nursing-mental-health': {
    metaTitle: 'Mental Health Nursing Flashcards | Free Study Cards',
    metaDescription: 'Practice key mental health conditions, nursing assessments and therapeutic approaches with free Nursing flashcards on Flashcard Maker. Built for student nurses and NMC revision.',
    h1: 'Mental Health Nursing Flashcards',
    h2: 'Free Nursing Cards for Mental Health Placements',
    intro: 'These free Nursing flashcards cover mental health conditions, therapeutic communication, risk assessment and the key medications used in mental health care. Ideal for student nurse revision.',
  },
  'free-flashcards-for-medicine-respiratory-system': {
    metaTitle: 'Respiratory System Flashcards | Free Medical Cards',
    metaDescription: 'Study the anatomy of the lungs, breathing mechanics, gas exchange and respiratory conditions with free Medical flashcards on Flashcard Maker. Great for medical and nursing students.',
    h1: 'Respiratory System Flashcards',
    h2: 'Free Medical Science Revision Cards',
    intro: 'Cover the anatomy of the lungs, the mechanics of breathing, gas exchange at the alveoli and common respiratory conditions with these free Medical Science flashcards.',
  },
  'free-flashcards-for-anatomy-digestive-system': {
    metaTitle: 'Digestive System Anatomy Flashcards | Free Cards',
    metaDescription: 'Revise the anatomy of the digestive tract, organs, enzymes and absorption processes with free Anatomy flashcards on Flashcard Maker. Great for nursing and medical students.',
    h1: 'Digestive System Anatomy Flashcards',
    h2: 'Free Anatomy Cards for Nursing and Medicine Students',
    intro: 'From the oral cavity to the large intestine, these free Anatomy flashcards take you through the structure and function of each organ in the digestive tract. Useful for nursing and medical revision.',
  },
  'free-flashcards-for-nursing-infection-control': {
    metaTitle: 'Infection Control Flashcards | Free Nursing Cards',
    metaDescription: 'Practice hand hygiene, PPE, standard precautions and isolation procedures with free Nursing flashcards on Flashcard Maker. Essential revision for student nurses.',
    h1: 'Infection Control Nursing Flashcards',
    h2: 'Free Nursing Study Cards on Infection Prevention',
    intro: 'These free Nursing flashcards cover the principles of infection prevention and control, including the chain of infection, standard precautions, PPE use and hand hygiene protocols.',
  },
  'free-flashcards-for-business-studies-marketing': {
    metaTitle: 'Marketing Flashcards | Free Business Studies Cards',
    metaDescription: 'Revise the marketing mix, market research, branding and segmentation with free Business Studies flashcards on Flashcard Maker. Covers GCSE and A Level content.',
    h1: 'Marketing Flashcards for Business Studies',
    h2: 'Free Business Studies Revision Cards',
    intro: 'Cover the marketing mix, market research methods, targeting and segmentation, branding and promotional strategies with these free Business Studies flashcards. Ideal for GCSE and A Level revision.',
  },
  'free-flashcards-for-sociology-education': {
    metaTitle: 'Sociology of Education Flashcards | Free Study Cards',
    metaDescription: 'Study sociological theories of education, educational inequality and labelling with free Sociology flashcards on Flashcard Maker. Built for A Level Sociology students.',
    h1: 'Sociology of Education Flashcards',
    h2: 'Free A Level Sociology Revision Cards on Flashcard Maker',
    intro: 'From functionalist and Marxist views on education to the factors affecting educational achievement and the hidden curriculum, these free Sociology flashcards cover the key theories and evidence.',
  },
};
